[project]
name = "spark-jobs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "delta-spark>=4.0.1",
    "pyspark>=4.1.1",
]
